name: Server

on: [ push ]

defaults:
  run:
    working-directory: .

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0
      -
        name: QEMU
        uses: docker/setup-qemu-action@v1.2.0
      -
        name: BuildX
        uses: docker/setup-buildx-action@v1.6.0
      -
        name: Authorization
        uses: docker/login-action@v1.13.0
        with:
          username: iantorres
          password: ${{ secrets.DOCKER_HUB_AUTHENTICATION_TOKEN }}
      -
        name: B & P
        id: docker_build
        uses: docker/build-push-action@v2.9.0
        with:
          push: false
          tags: iantorres/instance:latest
          context: .
          file: Dockerfile
          no-cache: true
      -
        name: Digest
        run: echo ${{ steps.docker_build.outputs.digest }}